image: maven:3-openjdk-18-slim

variables:
  MAVEN_OPTS: "-Dhttps.proxyHost=proxy-serveur.univ-nantes.prive -Dhttps.proxyPort=3128 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

stages:
  - test
  - deploy

services:
  - name: docker-registry.univ-nantes.fr/e206597m/trivial_pursuit_full_stack/hsqldb:v1
    alias: bdd

cache:
  paths:
    - trivial_pursuit_server/.m2/repository



unit-test:
  stage: test
  script:
    - cd trivial_pursuit_server
    - mvn $MAVEN_CLI_OPTS test



coverage-jacoco:
  stage: test
  script:
    - cd trivial_pursuit_server
    - mvn clean jacoco:prepare-agent package jacoco:report
  artifacts:
    when: always
    paths:
      - trivial_pursuit_server/trivialPursuitServer-api/target/site
      - trivial_pursuit_server/trivialPursuitServer-core/target/site
      - trivial_pursuit_server/trivialPursuitServer-data/target/site
      - trivial_pursuit_server/trivialPursuitServer-websocket-controller/target/site



mutation-pit:
  stage: test
  script:
    - cd trivial_pursuit_server
    - mvn clean package pitest:mutationCoverage
  artifacts:
    when: always
    paths:
      - trivial_pursuit_server/trivialPursuitServer-api/target/pit-reports
      - trivial_pursuit_server/trivialPursuitServer-core/target/pit-reports
      - trivial_pursuit_server/trivialPursuitServer-data/target/pit-reports
      - trivial_pursuit_server/trivialPursuitServer-websocket-controller/target/pit-reports



pages:
  stage: deploy
  needs:
    - job: unit-test
    - job: coverage-jacoco
    - job: mutation-pit
  interruptible: true
  script:
    - rm -rf public
    - mkdir public
    - cd public
    - mkdir -p api/{jacoco,pit}

    - mkdir -p core/{jacoco,pit}

    - mkdir -p data/{jacoco,pit}

    - mkdir -p websocket/{jacoco,pit}

    - cd ..
    - mv trivial_pursuit_server/index.html public

    - mv trivial_pursuit_server/trivialPursuitServer-api/target/site/jacoco/* public/api/jacoco
    - mv trivial_pursuit_server/trivialPursuitServer-api/target/pit-reports/* public/api/pit

    - mv trivial_pursuit_server/trivialPursuitServer-core/target/site/jacoco/* public/core/jacoco
    - mv trivial_pursuit_server/trivialPursuitServer-core/target/pit-reports/* public/core/pit

    - mv trivial_pursuit_server/trivialPursuitServer-data/target/site/jacoco/* public/data/jacoco
    - mv trivial_pursuit_server/trivialPursuitServer-data/target/pit-reports/* public/data/pit

    - mv trivial_pursuit_server/trivialPursuitServer-websocket-controller/target/site/jacoco/* public/websocket/jacoco
    - mv trivial_pursuit_server/trivialPursuitServer-websocket-controller/target/pit-reports/* public/websocket/pit

  artifacts:
    paths:
      - public
