image: maven:3-openjdk-18-slim

variables:
  MAVEN_OPTS: "-Dhttps.proxyHost=proxy-serveur.univ-nantes.prive -Dhttps.proxyPort=3128 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

stages:
  - test
  - coverage
  - deploy

services:
  - name: docker-registry.univ-nantes.fr/e206597m/trivial_pursuit_full_stack/hsqldb:v1
    alias: bdd

cache:
  paths:
    - .m2/repository/

unit-test:
  stage: test
  script:
    - cd trivial_pursuit_server
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - ./target/surefire-reports/TEST-*.xml
        - ./target/failsafe-reports/TEST-*.xml

jacoco-pitest:
  stage: coverage
  script:
    - cd trivial_pursuit_server
    - mvn $MAVEN_CLI_OPTS verify
  artifacts:
    when: always


pages:
  stage: deploy
  dependencies:
    - unit-test
    - jacoco-pitest
  interruptible: true
  script:
    - cd trivial_pursuit_server/trivialPursuitServer-core
    - mvn clean jacoco:prepare-agent install jacoco:report
    - rm -rf public
    - mkdir public
    - mv target/site/* public
#    - cd ../trivialPursuitServer-websocket-controller
#    - mvn clean jacoco:prepare-agent install jacoco:report
#    - rm -rf public
#    - mkdir public
#    - mv target/site/* public
  artifacts:
    paths:
      - public
